const palavras = [
{ word: "AMOR", hint: "Sentimento" },
{ word: "CARRO", hint: "Meio de transporte" },
{ word: "LIVRO", hint: "Objeto de leitura" },
{ word: "CACHORRO", hint: "Animal de estimação" },
{ word: "PIZZA", hint: "Comida popular" },
{ word: "CASA", hint: "Local de moradia" },
{ word: "MONTANHA", hint: "Formação geológica" },
{ word: "GATO", hint: "Animal de estimação" },
{ word: "CEREJA", hint: "Fruta pequena e vermelha" },
{ word: "AVIÃO", hint: "Meio de transporte aéreo" },
{ word: "VIOLÃO", hint: "Instrumento musical" },
{ word: "FUTEBOL", hint: "Esporte popular" },
{ word: "OCEANO", hint: "Grande massa de água salgada" },
{ word: "SOL", hint: "Estrela do nosso sistema" },
{ word: "ESCOLA", hint: "Local de aprendizado" },
{ word: "BICICLETA", hint: "Meio de transporte com pedais" },
{ word: "DINHEIRO", hint: "Meio de pagamento" },
{ word: "CAMINHÃO", hint: "Veículo de carga" },
{ word: "TELEVISÃO", hint: "Aparelho de mídia" },
{ word: "MONITOR", hint: "Equipamento de computador" },
{ word: "BANANA", hint: "Fruta amarela" },
{ word: "COBRA", hint: "Réptil sem pernas" },
{ word: "ABACAXI", hint: "Fruta tropical" },
{ word: "ELEFANTE", hint: "Animal grande com tromba" },
{ word: "CAFÉ", hint: "Bebida estimulante" },
{ word: "ASTRONAUTA", hint: "Profissional que viaja ao espaço" },
{ word: "FERROVIÁRIO", hint: "Relacionado a trens" },
{ word: "ESPINHA", hint: "Problema de pele" },
{ word: "SABÃO", hint: "Produto de limpeza" },
{ word: "BARCO", hint: "Meio de transporte aquático" },
{ word: "TELHADO", hint: "Parte superior de uma casa" },
{ word: "ELETRICIDADE", hint: "Fonte de energia" },
{ word: "PIRULITO", hint: "Doce no palito" },
{ word: "JANELA", hint: "Abertura na parede" },
{ word: "PASSARINHO", hint: "Pássaro pequeno" },
{ word: "MARTE", hint: "Planeta vermelho" },
{ word: "VENTO", hint: "Movimento do ar" },
{ word: "NEVE", hint: "Precipitação branca" },
{ word: "PORTA", hint: "Abertura de entrada" },
{ word: "COZINHA", hint: "Local de preparo de alimentos" },
{ word: "RÁDIO", hint: "Aparelho de comunicação" },
{ word: "PRAIA", hint: "Faixa de areia à beira-mar" },
{ word: "JORNAL", hint: "Publicação diária" },
{ word: "ÓCULOS", hint: "Acessório de visão" },
{ word: "RELOGIO", hint: "Instrumento de medição de tempo" },
{ word: "BRINQUEDO", hint: "Objeto de diversão" },
{ word: "CELULAR", hint: "Dispositivo de comunicação" },
{ word: "COMPUTADOR", hint: "Máquina de processamento de dados" },
{ word: "PLANETA", hint: "Corpo celeste" },
{ word: "INVERNO", hint: "Estação fria" },
{ word: "PRIMAVERA", hint: "Estação das flores" },
{ word: "SORVETE", hint: "Sobremesa gelada" },
{ word: "ABACATE", hint: "Fruta verde" },
{ word: "TATUAGEM", hint: "Desenho permanente na pele" },
{ word: "ESCORREGADOR", hint: "Brinquedo de parque" },
{ word: "TREM", hint: "Meio de transporte ferroviário" },
{ word: "QUEIJO", hint: "Alimento derivado do leite" },
{ word: "CASTELO", hint: "Fortaleza antiga" },
{ word: "ESTRELA", hint: "Corpo celeste brilhante" },
{ word: "TERRA", hint: "Nosso planeta" },
{ word: "LUA", hint: "Satélite natural" },
{ word: "ZEBRA", hint: "Animal listrado" },
{ word: "ROSA", hint: "Flor com espinhos" },
{ word: "BICICLETA", hint: "Veículo de duas rodas" },
{ word: "ESCADA", hint: "Estrutura para subir" },
{ word: "TELA", hint: "Superfície de exibição" },
{ word: "BANCO", hint: "Instituição financeira" },
{ word: "FÉRIAS", hint: "Período de descanso" },
{ word: "CHUVA", hint: "Precipitação de água" },
{ word: "TROVÃO", hint: "Som de tempestade" },
{ word: "RELÂMPAGO", hint: "Flash de luz" },
{ word: "GELO", hint: "Água congelada" },
{ word: "MÁQUINA", hint: "Dispositivo mecânico" },
{ word: "CÂMERA", hint: "Equipamento de fotografia" },
{ word: "TELEFONE", hint: "Dispositivo de comunicação" },
{ word: "MOTO", hint: "Veículo de duas rodas" },
{ word: "CRIANÇA", hint: "Pessoa jovem" },
{ word: "PASSEIO", hint: "Atividade de lazer" },
{ word: "CONCHA", hint: "Estrutura de proteção de moluscos" },
{ word: "VIDRO", hint: "Material transparente" },
{ word: "JANELA", hint: "Abertura para luz e ar" },
{ word: "CARPETA", hint: "Cobertura de chão" },
{ word: "CARRO", hint: "Veículo de quatro rodas" },
{ word: "ALMOFADA", hint: "Objeto de conforto" },
{ word: "CAFÉ", hint: "Bebida estimulante" },
{ word: "CHÁ", hint: "Bebida quente" },
{ word: "VINHO", hint: "Bebida alcoólica" },
{ word: "BALEIA", hint: "Animal marinho" },
{ word: "TUBARÃO", hint: "Predador marinho" },
{ word: "GOLFINHO", hint: "Mamífero marinho" },
{ word: "ARANHA", hint: "Animal aracnídeo" },
{ word: "BORBOLETA", hint: "Inseto colorido" },
{ word: "CAMINHADA", hint: "Atividade ao ar livre" },
{ word: "JARDIM", hint: "Área de cultivo" },
{ word: "PASSEIO", hint: "Atividade de lazer" },
{ word: "CORRIDA", hint: "Atividade física" },
{ word: "JANTAR", hint: "Refeição noturna" },
{ word: "BICICLETA", hint: "Veículo com pedais" },
{ word: "MELANCIA", hint: "Fruta grande e doce" },
{ word: "CELULAR", hint: "Dispositivo portátil" },
{ word: "PARQUE", hint: "Área de lazer ao ar livre" },
{ word: "PISCINA", hint: "Local de natação" },
{ word: "CADEIRA", hint: "Objeto para sentar" },
{ word: "BALCÃO", hint: "Superfície de apoio" },
{ word: "FÁBRICA", hint: "Local de produção" },{ word: "ALVORADA", hint: "Amanhecer" },
{ word: "ARQUITETURA", hint: "Estudo de construção" },
{ word: "BIBLIOTECA", hint: "Lugar de livros" },
{ word: "CAMAROEIRO", hint: "Pescador de camarão" },
{ word: "DIACONATO", hint: "Ofício religioso" },
{ word: "EQUINÓCIO", hint: "Fenômeno astronômico" },
{ word: "FERROVIÁRIO", hint: "Profissional de trens" },
{ word: "GIRAFA", hint: "Animal de pescoço longo" },
{ word: "HARMÔNICO", hint: "Relativo à harmonia" },
{ word: "INABITADO", hint: "Lugar deserto" },
{ word: "JATOESCALADO", hint: "Aparelho de ar" },
{ word: "LICENCIATURA", hint: "Curso de graduação" },
{ word: "MANGUEIRAL", hint: "Conjunto de mangueiras" },
{ word: "NEUROCIRURGIA", hint: "Cirurgia cerebral" },
{ word: "OROBÓ", hint: "Município Pernambucano" },
{ word: "PREDOMINANTE", hint: "Que prevalece" },
{ word: "QUARENTENA", hint: "Período de isolamento" },
{ word: "REPROVADO", hint: "Não aprovado" },
{ word: "SENTINELA", hint: "Vigilante" },
{ word: "TRANSCENDENTAL", hint: "Muito além" },
{ word: "ULTRAPASSAGEM", hint: "Ato de ultrapassar" },
{ word: "VERTICILADO", hint: "Disposição em verticilos" },
{ word: "ZELADORIA", hint: "Cuidado de edifício" },
{ word: "BALANCIAR", hint: "Ato de balançar" },
{ word: "CINESIOLOGIA", hint: "Estudo do movimento" },
{ word: "DIRETRIZ", hint: "Orientação principal" },
{ word: "EMPIRISMO", hint: "Teoria do conhecimento" },
{ word: "FLUTUAÇÃO", hint: "Ato de flutuar" },
{ word: "GESTICULAR", hint: "Usar gestos" },
{ word: "HERBÍVORO", hint: "Que come plantas" },
{ word: "INCERTEZA", hint: "Falta de certeza" },
{ word: "JUNÇÃO", hint: "Ato de unir" },
{ word: "LAMINADO", hint: "Revestido com lâminas" },
{ word: "MAGNÍFICO", hint: "Imponente" },
{ word: "NITROGLICERINA", hint: "Explosivo líquido" },
{ word: "OBSTETRÍCIA", hint: "Ramo da medicina" },
{ word: "PERCEPÇÃO", hint: "Ato de perceber" },
{ word: "QUIMERA", hint: "Sonho ou fantasia" },
{ word: "RESPLENDOR", hint: "Brilho intenso" },
{ word: "SINONÍMIA", hint: "Uso de sinônimos" },
{ word: "TERMOELÉTRICA", hint: "Tipo de usina" },
{ word: "UNICIDADE", hint: "Qualidade de único" },
{ word: "VEROSSIMILHANÇA", hint: "Aparência de verdade" },
{ word: "ZIRCÔNIA", hint: "Mineral" },
{ word: "AUTOSSUFICIÊNCIA", hint: "Capacidade de bastar-se" },
{ word: "BIZARRICE", hint: "Excentricidade" },
{ word: "COMPENDIAR", hint: "Resumir" },
{ word: "DISPOSIÇÃO", hint: "Arranjo ou ordem" },
{ word: "EFICIÊNCIA", hint: "Capacidade produtiva" },
{ word: "FOTOSSÍNTESE", hint: "Processo vegetal" },
{ word: "GEOFÍSICO", hint: "Relativo à geofísica" },
{ word: "HOSPITALEIRO", hint: "Acolhedor" },
{ word: "IMPROVISADO", hint: "Feito sem preparação" },
{ word: "JUGULAR", hint: "Veia do pescoço" },
{ word: "LATITUDINÁRIO", hint: "Relativo à latitude" },
{ word: "METICULOSO", hint: "Excessivamente cuidadoso" },
{ word: "NEOPLASIA", hint: "Novo crescimento de tecido" },
{ word: "ORDENHADOR", hint: "Que ordenha" },
{ word: "POTENCIAL", hint: "Capacidade de desenvolvimento" },
{ word: "QUINTESSÊNCIA", hint: "Parte mais pura" },
{ word: "REPUTAÇÃO", hint: "Conceito ou fama" },
{ word: "SATISFATORIAMENTE", hint: "De maneira satisfatória" },
{ word: "TERRAPLENAGEM", hint: "Nivelamento de terreno" },
{ word: "UNILATERAL", hint: "Que envolve um só lado" },
{ word: "VINCULAR", hint: "Ato de ligar" },
{ word: "ZOOARQUEOLOGIA", hint: "Estudo de restos animais" },
{ word: "AMBIVALÊNCIA", hint: "Dupla tendência" },
{ word: "BIODEGRADÁVEL", hint: "Que se decompõe" },
{ word: "CARTOGRAFIA", hint: "Ciência dos mapas" },
{ word: "DETERIORAÇÃO", hint: "Ato de deteriorar" },
{ word: "EXCLUSIVIDADE", hint: "Qualidade de exclusivo" },
{ word: "FISIOTERAPIA", hint: "Tratamento terapêutico" },
{ word: "GEOTÉRMICO", hint: "Relativo ao calor da Terra" },
{ word: "HIPOTERMIA", hint: "Temperatura corporal baixa" },
{ word: "INFLAMÁVEL", hint: "Que pega fogo" },
{ word: "JUBILAÇÃO", hint: "Estado de júbilo" },
{ word: "LEGISLATIVO", hint: "Relativo a leis" },
{ word: "MEGALOMANIA", hint: "Obsessão por grandeza" },
{ word: "NEUROTRANSMISSOR", hint: "Substância química no sistema nervoso" },
{ word: "ODONTOLOGIA", hint: "Estudo dos dentes" },
{ word: "PERSISTÊNCIA", hint: "Ato de persistir" },
{ word: "QUIROMANCIA", hint: "Adivinhação pelas mãos" },
{ word: "RECIPROCIDADE", hint: "Troca mútua" },
{ word: "SUSTENTABILIDADE", hint: "Uso responsável dos recursos" },
{ word: "TALASSOTERAPIA", hint: "Tratamento com água do mar" },
{ word: "UNIPOTENTE", hint: "Capacidade de formar um único tipo" },
{ word: "VIRTUOSIDADE", hint: "Excelência" },
{ word: "ZENITAL", hint: "Relativo ao zênite" },
{ word: "AUTOESTIMA", hint: "Valorização de si próprio" },
{ word: "BOMBARDEIRO", hint: "Avião militar" },
{ word: "CONJECTURA", hint: "Suposição" },
{ word: "DESSALINIZAÇÃO", hint: "Remoção de sal" },
{ word: "ENDOSCOPIA", hint: "Exame interno" },
{ word: "FOTOGÊNICO", hint: "Aparência boa em fotos" },
{ word: "GEOPOLÍTICA", hint: "Estudo da política e geografia" },
{ word: "HIDRÓFOBO", hint: "Que repele a água" },
{ word: "INEXORÁVEL", hint: "Implacável" },
{ word: "JUJUBA", hint: "Doce de goma" },
{ word: "LEPROLOGIA", hint: "Estudo da lepra" },
{ word: "STRANGER THINGS", hint: "Ficção científica e terror" },
{ word: "THE CROWN", hint: "Monarquia britânica" },
{ word: "MONEY HEIST", hint: "Assalto planejado" },
{ word: "BRIDGERTON", hint: "Romance histórico" },
{ word: "THE WITCHER", hint: "Caçador de monstros" },
{ word: "OZARK", hint: "Lavagem de dinheiro" },
{ word: "BLACK MIRROR", hint: "Tecnologia distópica" },
{ word: "THE UMBRELLA ACADEMY", hint: "Família de super-heróis" },
{ word: "LUCIFER", hint: "Diabo na Terra" },
{ word: "NARCOS", hint: "Tráfico de drogas" },
{ word: "DAREDEVIL", hint: "Herói cego" },
{ word: "THE QUEEN'S GAMBIT", hint: "Jogadora de xadrez" },
{ word: "SHADOW AND BONE", hint: "Fantasia e magia" },
{ word: "THE HAUNTING OF HILL HOUSE", hint: "Casa assombrada" },
{ word: "YOU", hint: "Obsessão perigosa" },
{ word: "13 REASONS WHY", hint: "Drama adolescente" },
{ word: "ORANGE IS THE NEW BLACK", hint: "Prisão feminina" },
{ word: "HOUSE OF CARDS", hint: "Drama político" },
{ word: "LOST IN SPACE", hint: "Aventura no espaço" },
{ word: "THE SOCIETY", hint: "Adolescentes sem adultos" },
{ word: "LOCKE & KEY", hint: "Casa mágica" },
{ word: "A SERIES OF UNFORTUNATE EVENTS", hint: "Desventuras infantis" },
{ word: "ALTERED CARBON", hint: "Ficção científica cyberpunk" },
{ word: "CHEF'S TABLE", hint: "Documentário culinário" },
{ word: "DARK", hint: "Mistério temporal" },
{ word: "EMILY IN PARIS", hint: "Comédia romântica" },
{ word: "GINNY & GEORGIA", hint: "Drama familiar" },
{ word: "LOVE DEATH & ROBOTS", hint: "Animação antológica" },
{ word: "QUEER EYE", hint: "Reality de transformação" },
{ word: "SEX EDUCATION", hint: "Comédia adolescente" },
{ word: "RICK E MORTY", hint: "Viagens interdimensionais" },
{ word: "BOJACK HORSEMAN", hint: "Cavalo ator" },
{ word: "HORA DE AVENTURA", hint: "Aventuras em um mundo mágico" },
{ word: "SOUTH PARK", hint: "Comédia satírica" },
{ word: "GRAVITY FALLS", hint: "Mistérios na floresta" },
{ word: "OS SIMPSONS", hint: "Família amarela" },
{ word: "UMA FAMÍLIA DA PESADA", hint: "Família irreverente" },
{ word: "STEVEN UNIVERSO", hint: "Aventuras cósmicas" },
{ word: "SCOOBY-DOO", hint: "Cão detetive" },
{ word: "BOB ESPONJA CALÇA QUADRADA", hint: "Fenda do Biquíni" },
{ word: "PHINEAS E FERB", hint: "Verão interminável" },
{ word: "JOVENS TITÃS EM AÇÃO", hint: "Heróis adolescentes" },
{ word: "POKEMON", hint: "Capturar monstros" },
{ word: "DRAGON BALL Z", hint: "Lutas épicas" },
{ word: "NARUTO", hint: "Ninja em treinamento" },
{ word: "MY HERO ACADEMIA", hint: "Super-heróis estudantes" },
{ word: "AVATAR: A LENDA DE AANG", hint: "Dominador dos elementos" },
{ word: "OS LOONEY TUNES", hint: "Personagens clássicos" },
{ word: "OS PADRINHOS MÁGICOS", hint: "Padrinhos mágicos" },
{ word: "AS MENINAS SUPERPODEROSAS", hint: "Super-heroínas meninas" },
{ word: "DORA A AVENTUREIRA", hint: "Exploradora jovem" },
{ word: "ARTHUR", hint: "Aventuras escolares" },
{ word: "DUCKTALES: OS CAÇADORES DE AVENTURAS", hint: "Patos aventureiros" },
{ word: "RUGRATS: OS ANJINHOS", hint: "Bebês aventureiros" },
{ word: "A VIAGEM DE CHIHIRO", hint: "Animação japonesa" },
{ word: "CASTLEVANIA", hint: "Caçadores de vampiros" },
{ word: "VOLTRON: O DEFENSOR LENDÁRIO", hint: "Robô gigante" },
{ word: "COWBOY BEBOP", hint: "Caçadores de recompensas" },
{ word: "FULLMETAL ALCHEMIST", hint: "Alquimistas irmãos" },
{ word: "ONE PIECE", hint: "Piratas aventureiros" }

];

// Exporta a lista para ser usada em outros arquivos
module.exports = palavras;
